on: push
name: build
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - shell: pwsh
        run: |
          rustup target add i686-pc-windows-gnu
          Invoke-WebRequest -Uri https://gnupg.org/ftp/gcrypt/binary/gnupg-w32-2.2.21_20200709.exe -OutFile C:\Temp\gnupg-32.exe
          C:\Temp\gnupg-32.exe /S
          Get-ChildItem -Path "C:\\Program Files (x86)"
