name: build
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo build
  test:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo test
          cargo clippy
