name: build
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt install libgpg-error-dev libgpgme-dev
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo build
  test:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - run: |
          sudo apt install libgpg-error-dev libgpgme-dev gpg
          gpg --import tests/resources/*
          gpg --list-secret-keys
          gpg --list-keys
          echo "test" > test
          gpg --encrypt --recipient passrs-tests@nocht.io test
          gpg --decrypt test.gpg
      - run: |
          cargo test
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.20.0"
          args: "-- --test-threads 1"
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
  lint:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt install libgpg-error-dev libgpgme-dev
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo clippy
